module.exports = {
  user: {
    userNotFound: "User not found",
    userFound: "User found",
    listShared: "List of shared users",
    userUpdated: "User updated successfully",
    userValidated: "User validated successfully",
    registered: "User Registered successfully",
    loggedIn: "User logged in successfully",
    passwordReset: "Password reset successfully",
    tempPassword: "Temporary password sent to your email",
    success: "Success",
    delete: "Successfully deleted",
    refreshToken: "token generated successfully",
  },
  error: {
    errorRegistering: "Error registering user",
    errorLoggingIn: "Error logging in user",
    errorUploading: "Error uploading image",
    errorGettingUser: "Error getting user",
    errorResettingPassword: "Error resetting password",
    passwordNotMatch: "Password and Confirm password does not match",
    invalidToken: "Invalid token",
    tokenEmpty: "No token is provided",
    tokenExpired: "Token expired",
    invalidPassword: "Invalid Password",
    invalidBody: "Invalid body fields",
    unprocessableEntity: "Validation Error",
    internalServerError: "Internal Server Error",
    failed: "Failed",
  },
};
